name: Update Snake
on:
  schedule:
    - cron: "0 0 * * *"  # Updates daily at midnight UTC
  workflow_dispatch:     # Allows manual runs
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg
      
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
