name: GitHub Snake Animation
on:
  schedule:
    - cron: "30 23 * * *"  # Runs daily at 23:30 UTC (30 mins before midnight)
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write  # Required to push to branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete commit history

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          min_contributions: 1  # Show animation even with few contributions
          show_other_dots: true  # Creates movement effect
          dot_size: 10           # Better visibility
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark
            assets/snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/
          git commit -m "Update snake animation [skip ci]"
          git push
