name: Snake Animation
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:     # Manual trigger
  push:
    branches: [ "main" ]

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required to push changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      - name: Generate snake graphics
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/snake.svg
            output/snake-dark.svg
            output/snake.gif
          min_contributions: 1  # Show even with few commits
          show_other_dots: true  # Create movement effect

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update snake animation [skip ci]"
          git push
