name: Update Snake Animation
on:
  schedule:
    - cron: "30 23 * * *"  # Runs daily before midnight UTC
  workflow_dispatch:       # Allows manual runs
  push:
    branches: [ "main" ]   # Runs when you push to main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required to push changes
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          show_other_dots: true  # ← Makes snake visible with few contributions
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg
            
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update snake animation"
          git push
